apps/right-to-rent-check/fields/index.js
apps/right-to-rent-check/index.js
apps/right-to-rent-check/translations/src/en/fields.json
package.json

- Use the new version of the date component that exposes the legend class to the template
- Fix the npm scripts to have a dev command and watch translations
This is reliant on the following PR for date component being merged and the version being bumped https://github.com/UKHomeOfficeForms/hof-component-date/pull/8

Create tenancy start page

---

package.json

The two hof packages were being installed but not used.
Lodash was being required, but not listed as a dependency.

Clean up unused/unspecified packages

---

assets/scss/app.scss
package.json

Because `hof` loads the latest theme by default if none is specified in the parent project then it is combining the old css from `hof-frontend-toolkit` and the new html from the theme at version 3.
By specifying the theme at version 2 then we ensure the html and css remain in sync.

Use hof-theme-govuk@2

---

apps/right-to-rent-check/behaviours/tenants.js
apps/right-to-rent-check/fields.js
apps/right-to-rent-check/index.js
apps/right-to-rent-check/translations/src/en/fields.json
apps/right-to-rent-check/translations/src/en/pages.json
apps/right-to-rent-check/translations/src/en/validation.json
apps/right-to-rent-check/views/content/tenant-another.md
apps/right-to-rent-check/views/tenant-another.html
assets/scss/app.scss
package.json
test/.eslintrc
test/common.js
test/mocha.opts
test/unit/behaviours/tenants.js

This PR adds commits for the `tenant-another/` step, which should present the added tenants and give the user an opportunity to add another tenant.
These commits load the view with the tenants details and the fields, from which a user can choose to add another tenant or not.
These commits do not incude the edit or delete features.
A second PR will be raised to address the edit/change feature of each tenant.

Add another tenant

---

package.json

Fix: Upgrade hof-theme-govuk 3.0.1 to fix the validation summary border not showing properly

---

apps/right-to-rent-check/acceptance/features/check-confirmed.js
apps/right-to-rent-check/acceptance/features/tenant-in-uk.js
apps/right-to-rent-check/acceptance/pages/uk-check-yourself.js
apps/right-to-rent-check/behaviours/rental-questions.js
apps/right-to-rent-check/behaviours/tenancy-start-postcode-check.js
apps/right-to-rent-check/index.js
apps/right-to-rent-check/translations/src/en/pages.json
apps/right-to-rent-check/views/check-confirmed.html
assets/scss/app.scss
codecept.conf.js
package.json
test/unit/behaviours/rental-questions.js
test/unit/behaviours/tenancy-start-postcode-check.test.js

1) Add the /check-confirmed step to the user journey and conditionally
present one of two sets of tabular data dependning on the users'
previous selection.
2) Fix /tenancy-start by saving the post data to the sessionModel. 
This was required because the post data was needed in the view of the /check-confirmed step

Add /check-confirmed step

---

apps/right-to-rent-check/acceptance/features/agent-address/address-step.js
apps/right-to-rent-check/acceptance/features/agent-address/lookup-step.js
apps/right-to-rent-check/acceptance/features/agent-address/manual-step.js
apps/right-to-rent-check/acceptance/features/agent-address/postcode-step.js
apps/right-to-rent-check/acceptance/features/agent-details.js
apps/right-to-rent-check/acceptance/features/declaration-dynamic-content.js
apps/right-to-rent-check/acceptance/features/tenant-in-uk.js
apps/right-to-rent-check/acceptance/pages/agent-address.js
apps/right-to-rent-check/index.js
apps/right-to-rent-check/translations/src/en/pages.json
apps/right-to-rent-check/translations/src/en/validation.json
codecept.conf.js
config.js

Add a new page to capture the Agent's address using a postcode or manual address entry.
The button text will be amended to 'Find address' once `hof-behaviour-address-lookup` is amended to allow customisation of the button text.

Agent address page and steps

---

apps/right-to-rent-check/acceptance/features/tenant-details.js
apps/right-to-rent-check/acceptance/pages/tenant-details.js
apps/right-to-rent-check/behaviours/age-restriction.js
apps/right-to-rent-check/index.js
apps/right-to-rent-check/translations/src/en/fields.json
apps/right-to-rent-check/translations/src/en/pages.json
apps/right-to-rent-check/translations/src/en/validation.json
package.json
test/unit/behaviours/age-restriction.test.js

- Add an age-restriction behaviour for under 18 validation
I couldn't just use [`before` argument in the config](https://github.com/UKHomeOfficeForms/hof-examples/blob/master/apps/date-component/README.md#date-argument) because I'm already using it for future DOB
Also, I explored the possibility of just using under 18 validation for future dates but this was voted ⬇️ by @karypun @Nadiahuq @jnicholson253

Update /tenant-details validation & content

---

apps/right-to-rent-check/acceptance/features/check-confirmed.js
apps/right-to-rent-check/acceptance/features/confirm/agent-in-property.js
apps/right-to-rent-check/acceptance/features/confirm/agent-not-in-property.js
apps/right-to-rent-check/acceptance/features/confirm/agent.js
apps/right-to-rent-check/acceptance/features/confirm/edit-a-tenant.js
apps/right-to-rent-check/acceptance/features/confirm/landlord-in-property.js
apps/right-to-rent-check/acceptance/features/confirm/landlord-not-in-property.js
apps/right-to-rent-check/acceptance/features/confirm/landlord.js
apps/right-to-rent-check/acceptance/features/landlord-name.js
apps/right-to-rent-check/acceptance/features/property-address.js
apps/right-to-rent-check/acceptance/features/tenancy-start/tenancy-start-backlink-submit.js
apps/right-to-rent-check/acceptance/features/tenancy-start/tenancy-start-date.js
apps/right-to-rent-check/acceptance/pages/current-property-address.js
apps/right-to-rent-check/acceptance/pages/property-address.js
apps/right-to-rent-check/behaviours/confirm-tenants.js
apps/right-to-rent-check/behaviours/rental-questions.js
apps/right-to-rent-check/behaviours/tenancy-start-postcode-check.js
apps/right-to-rent-check/behaviours/tenants.js
apps/right-to-rent-check/index.js
apps/right-to-rent-check/translations/src/en/pages.json
apps/right-to-rent-check/views/confirm.html
assets/scss/app.scss
mock-postcode.js
package.json
test/unit/behaviours/confirm-tenants.js
test/unit/behaviours/rental-questions.js
test/unit/behaviours/tenancy-start-postcode-check.test.js
test/unit/behaviours/tenants.js

Add a behaviour that extends the hof-behaviour-summary-page
with the ability to declare fields with children for the scenario
where a field may be saved as a collection
This is an image of how the tenants will be rendered.

Right to rent /confirm page and behaviour

---

apps/right-to-rent-check/acceptance/features/confirm/agent-not-in-property.js

* This causing the tests to fail
~~Sometimes this tests keeps the address data from a previous test because~~
The completeToStep method can go through various routes for the address, this test assumes it will take the user through the manual address step.  This is not always going to happen, sometimes it does an address lookup with `Cr0 2eu`.  Force the test to go through the postcode lookup step

Fix unreliability of agent-not-in-property acceptance

---

package.json

Update to hof-behaviour-address-lookup to 2.2.0

---

apps/right-to-rent-check/acceptance/features/confirm/agent-in-property.js
apps/right-to-rent-check/acceptance/features/confirm/landlord-in-property.js
apps/right-to-rent-check/behaviours/customer-email.js
apps/right-to-rent-check/behaviours/tenants.js
apps/right-to-rent-check/index.js
config.js

The format string was being spread around the codebase. Consolidate by moving it into configuration and ensuring we use a consistent format wherever formatted dates are displayed.
Fixes the formatting of the "move in date" field on the confirm page as a side-effect.

Make date formats a configurable parameter

---

apps/right-to-rent-check/behaviours/caseworker-email.js
apps/right-to-rent-check/emails/caseworker.html
apps/right-to-rent-check/index.js
apps/right-to-rent-check/translations/src/en/email.json
config.js

Send an email to a configured caseworker email address with a link to the generated PDF document containing application data.
Note: There are still a number of related known bugs around PDF generation and storage, but those aren't related to the email functionality itself.

[LCS-343] - Send caseworker emails on submission

---

apps/right-to-rent-check/fields.js
package.json

This is when javascript is turned off the countries where not displaying but just the translations

[LCS-371] - Fix: country typeahead with no JS

---

apps/right-to-rent-check/fields.js

These classes are required for typeahead functionality.

Restore className property that was accidentally removed

---

apps/right-to-rent-check/acceptance/features/confirm/agent-in-property.js
apps/right-to-rent-check/acceptance/features/confirm/agent.js
apps/right-to-rent-check/acceptance/features/confirm/edit-a-tenant.js

The postcodes need to be input in the postcode fields, otherwise a random postcode is used, and so the eventual assertions may not hold.

Fix functional test address inputs

---

apps/right-to-rent-check/acceptance/features/confirm/edit-a-tenant.js

I managed to remove a big block of code when working on #107 that didn't fail any tests. This is a test that covers that code.

Add test for confirm page edit tenant

---

apps/right-to-rent-check/acceptance/features/confirm/edit-tenant-documents.js
apps/right-to-rent-check/behaviours/confirm-tenants.js
test/unit/behaviours/confirm-tenants.js

Code that mapped fields from top level of model to tenants array was expecting fields to always be defined as strings. Because date of birth includes a parse function it was defined as an object so was not picked up.
Add a `map` to normalise field configuration to list of field keys.
Additionally cleans up some of the code and tests around this functionality to make them a little easier to read/follow - in particular swapping `foo`, `baz` for real-life field names.

[LCS-380] - Fix date of birth being removed from tenants array

---

apps/right-to-rent-check/acceptance/features/tenant-additional-details.js
apps/right-to-rent-check/acceptance/pages/tenant-additional-details.js
apps/right-to-rent-check/behaviours/tenants.js
test/unit/behaviours/tenants.js

Correctly unsets the checkboxes on the tenant-additional-details page so that they are not left pre-populated in certain circumstances.

[LCS-341] - Fix preselected tenant details checkboxes

---

apps/right-to-rent-check/translations/src/en/fields.json
apps/right-to-rent-check/translations/src/en/pages.json

Changes header and intro text.
Explicitly set page header in pages translation as it is more predictable to manage when all the page content is set in the same place, and not split between two different files.

[LCS-347] - Update content on documents check page

---

assets/scss/app.scss

Reduces the width of any postcode field using the govuk elements form styles defined here: https://govuk-elements.herokuapp.com/form-elements/example-form-elements/
The selector will be reliable because postcode field configuration is driven from the address lookup behaviour, and so the name of the fields will always contain `postcode`. There are some old browsers that won't support the selector, but they will revert to a standard width field.

[LCS-338] - Reduce width of postcode fields

---

apps/right-to-rent-check/acceptance/features/landlord-agent.js
apps/right-to-rent-check/acceptance/pages/landlord-or-agent.js
apps/right-to-rent-check/behaviours/confirm-tenants.js
test/unit/behaviours/confirm-tenants.js

When a field appears in more than one step then the logic to find the url to redirect to when editing the field can point to the wrong place. When checking which steps contain a field, add an additional check that the user has previously visited that step.

[LCS-385] - Ensure confirm page links to correct step on edit

---

apps/right-to-rent-check/index.js

I can't work out why some other pages display the appropriate step for the backbutton e.g. https://github.com/UKHomeOffice/right-to-rent-check/blob/master/apps/right-to-rent-check/views/check-not-needed-uk.html
But this one does not.
However, adding this explicit config seems to solve the problem

[LCS-375] Add back button for check not needed

---

apps/right-to-rent-check/acceptance/features/confirm/edit-landlord-address.js
package.json

Fix was in hof-behaviour-address-lookup but bump the version to the fix, and include a regression test.

Fix manual address being cleared on edit

---

apps/right-to-rent-check/index.js
apps/right-to-rent-check/views/content/cookies.md
apps/right-to-rent-check/views/content/privacy-policy.md
apps/right-to-rent-check/views/cookies.html
index.js
package.json

- Add pages for privacy-policy and cookies to override
inherited cooies resource and amend links in the footer.
- footer links include /cookies and /privacy-policy,
and not /terms-and-conditions
- Swtich off cookies and terms hof middleware

Add pages for privacy-policy and cookies

---

apps/right-to-rent-check/models/upload.js
test/unit/models/upload.js

When we send links to uploaded files to caseworkers we need them to have to login themselves to access the files (otherwise they would be insecure in email transit). Remove the pre-authed bearer token from the created url as this was originally used for firearms where files would be accessed by API.

Remove pre-authed bearer token from upload urls

---

apps/right-to-rent-check/views/content/cookies.md
apps/right-to-rent-check/views/content/privacy-policy.md
assets/scss/app.scss

Previously, we were overriding the govuk h1 styling by making it smaller.  This was against the standards and not as accessible
**Standard h1 styling**

Use default govuk h1 styling

---

.drone.yml

drone-trigger params must only have a single `$` opposed to docker where they need `$$`

fix param values in deploy triggers

---

.drone.yml

so as not to trigger all build steps after deploy and before smoke test

Build and test on master branch with push events
