UKHomeOffice/right-to-rent-check

.gitignore, Dockerfile, README.md, app.js, apps/right-to-rent-check/fields/index.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/fields.json, apps/right-to-rent-check/translations/src/en/journey.json, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/views/step.html, assets/js/index.js, assets/scss/app.scss, docker-compose.yml, hof.settings.json, index.js, package.json
Also
- Add a README about starting the app
- update the .gitignore
https://jira.digital.homeoffice.gov.uk/browse/LCS-225
=> Use the hof-generator 0.2.0 to generate the Right to rent check app

hof.settings.json
remove the session secret so our secrets (intended for the server) are not published
=> remove session secret

apps/right-to-rent-check/fields/index.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/fields.json, apps/right-to-rent-check/translations/src/en/journey.json, apps/right-to-rent-check/translations/src/en/pages.json, assets/js/index.js, assets/scss/app.scss, package.json
* Rebased with https://github.com/UKHomeOffice/right-to-rent-check/pull/4
Please merge above first before merging
* Use country selector
* Use the new date component
* Added styling taken from other hof apps
* Use latest hof-bootstrap
=> Add the tenant details page

.eslintignore, .eslintrc, .travis.yml, apps/right-to-rent-check/index.js, package.json
Remove redundant hof-component-date variable in steps file
=> Add travis

.drone.yml
run a container for the acceptance tests so they can be run against the service in Drone CI
=> build acceptance tests with drone CI

apps/right-to-rent-check/acceptance/features/agent-details.js, apps/right-to-rent-check/acceptance/pages/agent-details.js, apps/right-to-rent-check/acceptance/pages/landlord-name.js, apps/right-to-rent-check/fields/index.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/fields.json, apps/right-to-rent-check/translations/src/en/pages.json, codecept.conf.js, package.json
=> Add agent-details page and acceptance

apps/right-to-rent-check/acceptance/features/landlord-name.js, apps/right-to-rent-check/acceptance/pages/landlord-address.js, apps/right-to-rent-check/acceptance/pages/landlord-name.js, apps/right-to-rent-check/fields/index.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/fields.json, codecept.conf.js
https://jira.digital.homeoffice.gov.uk/browse/LCS-219
=> Add landlord-name page and acceptance tests

apps/right-to-rent-check/acceptance/pages/landlord-name.js, apps/right-to-rent-check/fields.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/fields.json, apps/right-to-rent-check/translations/src/en/validation.json
* renamed landlord-name to landlord-name-agent as this is a field used elsewhere if you are the landlord
=> added missing validation messages from end-tenancy

apps/right-to-rent-check/acceptance/features/start.js, apps/right-to-rent-check/acceptance/pages/check-you-can-use.js, apps/right-to-rent-check/acceptance/pages/start.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/buttons.json, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/views/content/start-final.md, apps/right-to-rent-check/views/content/start-hidden.md, apps/right-to-rent-check/views/content/start-main.md, apps/right-to-rent-check/views/start.html, assets/scss/app.scss, codecept.conf.js, package.json
This PR needs merging https://github.com/UKHomeOfficeForms/hof-bootstrap/pull/132 
https://jira.digital.homeoffice.gov.uk/browse/LCS-200
=> Start page using markdown

Dockerfile, docker-compose.yml, run.sh
Copy over built assets (`/public`) after `install` and start app using correct file name (`app.js`)
Update dockerfile to use latest nginx proxy
=> Update command to start application

apps/right-to-rent-check/acceptance/features/check-you-can-use.js, apps/right-to-rent-check/acceptance/features/current-property-address.js, apps/right-to-rent-check/acceptance/features/person-in-property.js, apps/right-to-rent-check/acceptance/features/property-address.js, apps/right-to-rent-check/acceptance/pages/person-in-property.js, apps/right-to-rent-check/acceptance/pages/person-location.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/pages.json, codecept.conf.js
Add placeholder person-location step
Change the steps file to follow a new order as per request of designer/user researcher etc
https://jira.digital.homeoffice.gov.uk/browse/LCS-267
https://jira.digital.homeoffice.gov.uk/browse/LCS-287
=> Change property step to person-in-property and add content

.gitignore, apps/right-to-rent-check/views/partials/navigation.html
This is the link they want in every page https://www.gov.uk/check-tenant-right-to-rent-documents of the header, story item below
https://jira.digital.homeoffice.gov.uk/browse/LCS-175
=> Add an explicit url to the proposition

apps/right-to-rent-check/translations/src/en/pages.json
The work is done but just need to remove the placeholder text
https://jira.digital.homeoffice.gov.uk/browse/LCS-240
=> Remove check-you-can-use placeholder page

.travis.yml, package.json
=> Add travis build config

index.js, package.json
Use the latest hof iteration, and not hof-bootstrap
=> Update to latest hof

package.json
Following conversation with @karypun it's been decided to use the new govuk form styles for this project.
=> Update theme to v3

apps/right-to-rent-check/behaviours/filter-fields.js, apps/right-to-rent-check/fields.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/fields.json, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/translations/src/en/validation.json, apps/right-to-rent-check/views/content/tenant-additional-details.md, apps/right-to-rent-check/views/tenant-additional-details.html, assets/scss/app.scss
Per https://jira.digital.homeoffice.gov.uk/browse/LCS-208
Adds a new step, with 4 checkboxes for possible extra documentation that might be provided about a tenant. Checkboxes are optional, but if a checkbox is selected then the detail must be provided.
=> Add step to collect tenant's additional details

apps/right-to-rent-check/acceptance/features/session-error.js, package.json
- update hof an hof-theme-govuk
- test it with codecept
=> Session Timeout Button redirect to '/';

apps/right-to-rent-check/acceptance/features/tenant-in-uk.js, apps/right-to-rent-check/acceptance/pages/uk-check-yourself.js, apps/right-to-rent-check/fields.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/fields.json, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/translations/src/en/validation.json, codecept.conf.js
This was tested with a post huddle in the team
https://jira.digital.homeoffice.gov.uk/browse/LCS-245
=> Tenant-in-uk: Add the page & acceptance tests

apps/right-to-rent-check/acceptance/features/document-check-yourself.js, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/views/documents-check-yourself.html
https://jira.digital.homeoffice.gov.uk/browse/LCS-305
=> Document-check-yourself: Add page & acceptance

apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/translations/src/en/validation.json
- Address validation
- header for the current-property-address
=> Content update for addresses

apps/right-to-rent-check/acceptance/features/check-not-needed-location.js, apps/right-to-rent-check/acceptance/pages/check-not-needed-location.js, apps/right-to-rent-check/translations/src/en/fields.json, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/views/check-not-needed-location.html, apps/right-to-rent-check/views/content/check-not-needed-location.md, codecept.conf.js
An exit page used to inform the user its not necessary for them to apply.
=> Add page @ /check-not-needed-location

apps/right-to-rent-check/translations/src/en/buttons.json, package.json
- update includes tanslatable postcode submit button text
=> Update to latest hof-behaviour-address-lookup

apps/right-to-rent-check/acceptance/features/declaration-dynamic-content.js, apps/right-to-rent-check/acceptance/features/landlord-address/address-step.js, apps/right-to-rent-check/acceptance/features/landlord-address/lookup-step.js, apps/right-to-rent-check/acceptance/features/landlord-address/manual-step.js, apps/right-to-rent-check/acceptance/features/landlord-address/postcode-step.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/translations/src/en/validation.json
- add the landlord address page and acceptance tests
- make sure the address is a required field
- update the version of address behaviour
- set value fo postcode submit button
=> Landlord Address page

apps/right-to-rent-check/acceptance/features/tenant-another.js, apps/right-to-rent-check/acceptance/features/tenant-delete.js, apps/right-to-rent-check/behaviours/tenants.js, apps/right-to-rent-check/views/tenant-another.html, test/unit/behaviours/tenants.js
- The locals have been changed in tenants behaviour
- Also added a unit test to tenants behaviour to look for the dob to change
=> change date format for /tenant-another

apps/right-to-rent-check/behaviours/confirm-filter-sections.js, apps/right-to-rent-check/behaviours/dynamic-title.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/buttons.json, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/views/confirm.html, package.json, test/unit/behaviours/confirm-filter-sections.test.js, test/unit/behaviours/dynamic-title.test.js
Fixes the following:
* Missing header
* Date formatting of DOB
* Incorrect button text 
* Missing landlord address step on landlord journey
* Incorrect edit links for address fields
* Incorrect label for "Not provided" fields
* Agent details still showing when editing from agent to landlord
=> LCS-215 - Confirm page

Dockerfile-acceptance, apps/right-to-rent-check/behaviours/tenancy-start-postcode-check.js, config.js, run.sh, test.sh
Update the build scripts removing unavailable and unnecessary scripts
=> Amend build scripts

apps/right-to-rent-check/behaviours/pdf-uploader.js
=> Add debug to pdf uploader behaviour

apps/right-to-rent-check/behaviours/customer-email.js, apps/right-to-rent-check/emails/customer.html, apps/right-to-rent-check/fields.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/translations/src/en/email.json, apps/right-to-rent-check/translations/src/en/fields.json, apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/translations/src/en/validation.json, package.json
Sends an email to the applicant after a successful submission.
=> [LCS-282] - Customer email

apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/views/content/privacy-policy.md, apps/right-to-rent-check/views/layout.html, apps/right-to-rent-check/views/privacy-policy.html
Also add privacy-policy to the footer of the page
=> [LCS-280] New page /privacy-policy replace T&Cs

apps/right-to-rent-check/fields.js, apps/right-to-rent-check/translations/src/en/fields.json
If this isn't provided then it defaults to "Afghanistan"
=> Add null option to fallback country select

assets/scss/app.scss
=> [LCS-382] - Fix backlink icon

package.json
upgrades hof-form-wizard to 4.3.0
Fix- add defaultformatter for spaces, trims & hyphens
=> Upgrade hof to 13.0.1

apps/right-to-rent-check/behaviours/confirm-tenants.js, apps/right-to-rent-check/behaviours/pdf-uploader.js, apps/right-to-rent-check/behaviours/summary-sections.js, apps/right-to-rent-check/index.js, apps/right-to-rent-check/views/pdf.html, test/unit/behaviours/confirm-tenants.js, test/unit/behaviours/pdf-uploader.js, test/unit/behaviours/summary-sections.js
The PDFs were generating empty because the behaviour was expecting to be extending from the summary page behaviour, which was not the case.
=> [LCS-381] Fix empty application pdfs

apps/right-to-rent-check/translations/src/en/validation.json
add the missing validation messages and fix the path name for `property-address`
=> Fix validation messages for postcode and address

apps/right-to-rent-check/fields.js, apps/right-to-rent-check/translations/src/en/fields.json
also company field is optional
https://jira.digital.homeoffice.gov.uk/browse/LCS-353
=> [LCS-353] - Update /agent-details 

apps/right-to-rent-check/translations/src/en/fields.json
https://jira.digital.homeoffice.gov.uk/browse/LCS-352
=> [LCS-352] - Content update: /landlord-details

apps/right-to-rent-check/views/content/start-hidden.md
Now that hof is using showdown, it appears that the markdown was not displaying fully. I had to rewrite the bold part for it to display.  It appears that the current text has something that is not making it display
However, it's helpful to be able to put in html in the markdown.  It makes it more flexible
=> [LCS-403] - Amend start content markdown

apps/right-to-rent-check/translations/src/en/pages.json, apps/right-to-rent-check/views/pdf.html
=> [LCS-399] - Update PDF content & styling

package.json
This will allow the use .env to load environment variables which will speed up development
=> upgrade to hof-build 1.6.0

apps/right-to-rent-check/views/content/cookies.md, apps/right-to-rent-check/views/content/declaration.md, apps/right-to-rent-check/views/content/privacy-policy.md
- Make the heading larger
- open the privacy policy link in a new tab
=> [LCS 406] Amend privacy policy & cookies headings

.drone.yml
need this to push image to quay through drone ci
=> use user drone to push to quay

apps/right-to-rent-check/acceptance/features/tenant-details.js, apps/right-to-rent-check/fields.js
Also remove "Stateless, under the 1954 Convention"
https://jira.digital.homeoffice.gov.uk/browse/LCS-408
This has been changed at this level rather than hof so it does not affect other services
=> [LCS-408] Add Stateless to countries list

.gitignore, apps/right-to-rent-check/behaviours/caseworker-email.js, apps/right-to-rent-check/translations/src/en/email.json
https://jira.digital.homeoffice.gov.uk/browse/LCS-407
=> [LCS 407] - Add total tenants to caseworker email subject

apps/right-to-rent-check/behaviours/pdf-uploader.js, apps/right-to-rent-check/views/pdf.html
https://jira.digital.homeoffice.gov.uk/browse/LCS-409
=> [LCS-409] - Add date time stamp to caseworker email

.drone.yml, Dockerfile, Dockerfile-acceptance, apps/right-to-rent-check/acceptance/features/agent-details.js, apps/right-to-rent-check/acceptance/features/declaration-dynamic-content.js, apps/right-to-rent-check/acceptance/features/person-in-property.js, apps/right-to-rent-check/acceptance/features/rental-property-location.js, apps/right-to-rent-check/acceptance/features/request-another-tenant.js, apps/right-to-rent-check/acceptance/features/tenant-additional-details.js, apps/right-to-rent-check/acceptance/features/tenant-in-uk.js, codecept.conf.js, package.json
replace phantom driver with chrome driver
upgrade docker node to v8
ensure app not run as root
=> Use selenium/standalone-chrome
